# Generated by Django 5.0 on 2023-12-25 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 8, 9, 49, 106231, tzinfo=datetime.timezone.utc)),
        ),
    ]
