# Generated by Django 5.0.1 on 2024-01-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_dummymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyModel',
        ),
    ]
