# Generated by Django 4.2.7 on 2023-12-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableid', models.IntegerField(unique=True)),
                ('capacity', models.IntegerField()),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
    ]
