# Generated by Django 5.0 on 2024-01-01 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_menu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ManyToManyField(related_name='booking', to='booking.table'),
        ),
    ]
