# Generated by Django 5.0.1 on 2024-01-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_dummymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyModel',
        ),
    ]
