# Generated by Django 5.0.1 on 2024-01-16 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_delete_dummymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
